-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 26, 2019 at 10:22 PM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.3.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `yazlab`
--

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `id` bigint(20) NOT NULL,
  `name` varchar(150) DEFAULT NULL,
  `content` varchar(2000) DEFAULT NULL,
  `type` enum('gundem','spor','ekonomi','dunya') DEFAULT NULL,
  `image_link` varchar(250) DEFAULT NULL,
  `like_number` int(11) DEFAULT NULL,
  `dislike_number` int(11) DEFAULT NULL,
  `view_count` int(11) DEFAULT NULL,
  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`id`, `name`, `content`, `type`, `image_link`, `like_number`, `dislike_number`, `view_count`, `date`) VALUES
(1, 'Kılıçdaroğlu kendisine saldıranlardan şikayetçi oldu', 'CHP Genel Başkanı Kemal Kılıçdaroğlu, şehit cenazesinde kendisine saldıranlardan avukatı Celal Çelik aracılığıyla şikayetçi oldu.\r\n\r\nCHP Genel Başkanı Kılıçdaroğlu, Ankara\'nın Çubuk ilçesi Akkuzulu Mahallesi\'nde 21 Nisan Pazar günü şehit piyade sözleşmeli er Yener Kırıkcı\'nın cenaze töreni sonrasında uğradığı saldırıya ilişkin soruşturma kapsamında şüpheliler hakkında şikayette bulundu. Kılıçdaroğlu\'nun şikayet dilekçesinin avukatı Celal Çelik aracılığıyla başsavcılığa iletildiği öğrenildi.', 'gundem', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbef5ffc03c0e40ecf49b28.jpg', 2, 1, 1, '2019-04-26 20:20:38'),
(2, 'Galatasaray\'da yetişti, şimdi takımın yıldızı!', 'Galatasaray alt yapısından yetişen Berk İsmail Ünsal Sakaryaspor formasıylu bu sezon attığı 12 golle dikkatleri üzerine çekti.\r\n\r\nTFF 2. Lig Beyaz Grup\'ta Play-Off\'a kalmayı haftalar öncesinden garantileyen Sakaryaspor\'da Galatasaraylı eski golcü Berk İsmail Ünsal attığı gollerle dikkat çekiyor.\r\n\r\nSezon başında Sakaryaspor ile 1 yıllık sözleşme imzalayan 24 yaşındaki golcü futbolcu 27 maçta, 12 gol atarak takımın en golcü ismi olmayı başardı.\r\n\r\n1.90 boyundaki Berk, ligin 32. haftasında deplasmanda oynadıkları zorlu Kastamonuspor maçında attığı frikik golü ile takımına bir puanı kazandırmıştı.', 'spor', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbed2d4c03c0e40ecf497e1.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(3, 'Listeyi belirledi! 4 isimle yollar ayrılıyor...', 'Galatasaray Teknik Direktörü Fatih Terim, takımdan gönderilmesi için 4 isim belirledi. Deneyimli teknik adam, Muğdat, Semih Kaya, Ömer Bayram ve Sinan Gümüş ile devam etmek istemiyor.\r\n\r\nTakımın motivasyonunu bozmak istemeyen tecrübeli teknik adam, gönderilecekler listesini sezon bittikten sonra yönetime iletecek.', 'spor', 'https://ajssarimg.mediatriple.net/997377.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(4, 'Son dakika... Sri Lanka\'daki saldırıları DEAŞ üstlendi', 'Sri Lanka\'da 21 Nisan Pazar günü Paskalya Ayini sırasında kilise ve otelleri hedef alan, 321 kişinin hayatını kaybettiği ve 500\'den fazla kişinin yaralandığı saldırıları terör örgütü DEAŞ üstlendi.\r\n\r\nSri Lanka\'da 21 Nisan Pazar günü Paskalya Ayini sırasında kilise ve otelleri hedef alan, 321 kişinin hayatını kaybettiği ve 500\'den fazla kişinin yaralandığı saldırıları terör örgütü DEAŞ üstlendi.\r\n\r\nSri Lanka\'da pazar günü Hristiyanlar için kutsal Paskalya ayinlerinin düzenlendiği Kochchikade kentindeki St. Anthony\'s, Katana\'daki St. Sebastian ve Batticaloa\'daki Meryem Ana kiliseleri ile başkent Kolombo\'daki beş yıldızlı Shangri-La, Cinnamon Grand ve Kingsbury otellerine bombalı saldırılar gerçekleştirilmişti.', 'dunya', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbeefea0f25441e0c1081ff.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(5, 'Trump to make first state visit to UK in June', 'London (CNN)US President Donald Trump will make his first state visit to the United Kingdom in June, Buckingham Palace said Tuesday.\r\nThe visit will take place from June 3 to June 5, the palace said in a tweet. ', 'dunya', 'https://cdn.cnn.com/cnnnext/dam/assets/190423085251-trump-queen-windsor-castle-july-2018-medium-tease.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(6, 'Greenpeace: Plastik atıkların yeni adresi Türkiye, kontrolsüz bir şekilde çöp ithal ediyor', 'Çevre Örgütü Greenpeace\'in yayımladığı yeni rapora göre, Çin\'in yurt dışından plastik atık alımına 2018\'de yasak koymasının ardından, bu atıkların yeni adresi Endonezya ve Türkiye oldu.\r\nÇin\'deki yasak henüz uygulamaya girmeden plastik atık akışı Malezya, Vietnam ve Tayland\'a yönelmişti. Ancak bu ülkelerin de hızlı bir şekilde plastik ithalatına kısıtlamalar getirmesiyle plastik atık akışı Endonezya, Hindistan ve Türkiye\'ye kaydı.\r\n\r\nPlastik atıklarını ihraç eden ülkelerin başında ise ABD, Almanya, İngiltere ve Japonya geliyor.\r\n\r\nBBC Türkçe\'de yer alan habere göre Greenpeace Doğu Asya, \'2016-2018 dünya plastik atık ticareti verileri ve Çin\'in yurtdışından atık ithalini yasaklamasının etkileri\' başlıklı raporunu bugün yayımladı.\r\n\r\nRapor, 2016-2018 yılları arasında en fazla plastik atık ithal ve ihraç eden 21 ülkenin ithalat ve ihracat verilerini içeriyor.\r\nRapora göre plastik atık ihracatı, 2016 yılında 12,5 milyon tondan 2018\'de 5,8 milyon tona düşerek yaklaşık yüzde 50 oranında azaldı.\r\n\r\nAncak plastik üretiminin artacağı tahmin edildiğinden, plastik atık ihracatındaki bu düşüş, atıkların ülkelerde stoklanmaya ya da yanlış yöntemlerle bertaraf edilmeye başlanacağı anlamına geliyor.', 'gundem', 'https://cdntr2.img.sputniknews.com/images/102340/31/1023403109.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(7, 'Dünyanın en büyük tek günlük seçiminin etkisi de büyük: Sandık görevlileri aşırı yorgunluk nedeniyle yaşamını yitirdi', 'Dünyanın en büyük tek günlük seçimini 17 Nisan’da gerçekleştiren Endonezya’da, 90’dan fazla sandık görevlisi ‘aşırı yorgunluk’ nedeniyle yaşamını yitirdi.\r\nEndonezya’da 192 milyondan fazla seçmenin sandık başına gittiği seçimler kadar oy sayım süreci de zorlu geçiyor. Ülke çapında 92 sandık görevlisi aşırı yorgunluk nedeniyle yaşamını yitirdi.\r\n\r\nMaluku eyaletindeki Tanimbar Adaları’nda bulunan Adodo Molu köyünde sandık başkanı olan Selvianus Itranbey, seçim yorgunluğu nedeniyle yaşamını yitiren ilk kişi oldu. Itranbey’in oyların tekrar sayımı konusunda yapılan genel toplantı sırasında yaşamını yitirdiği belirtildi.\r\n\r\nUlusal Seçim Komisyonu tarafından yapılan açıklamada, uzun çalışma sürelerinin 91 sandık görevlisinin ölümüne yol açtığı kaydedildi. Bu açıklamayla birlikte yaşamını yitiren görevlilerin sayısı 92’ye yükseldi.\r\n\r\nKomisyon, 374 görevlinin de yorgunluğa bağlı rahatsızlıklar yaşadığını belirtti.', 'dunya', 'https://cdntr2.img.sputniknews.com/images//103885/00/1038850009.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(8, '\'It\'s clear we won\': Istanbul\'s new mayor keen to start work ', 'Ekrem İmamoğlu delivered a shock to the president but the fight for control of the city is not over\r\nThousands of people gathered in Istanbul’s seaside Maltepe district on Sunday to see a politician take the stage in dazzling spring sunshine, red Turkish flags fluttering in the wind.\r\n\r\nSuch scenes are normal in Recep Tayyip Erdoğan’s Turkey, but this rally wasn’t for him. It was for Istanbul’s new mayor, Ekrem İmamoğlu, who last month delivered one of the biggest challenges to Erdoğan’s grip on the country in years.\r\n\r\nLocal elections on 31 March proved to be an unexpected watershed moment in Turkish politics, as usually run-of-the-mill races for mayors and neighbourhood administrators became a referendum on Erdoğan’s handling of the faltering economy.\r\n\r\nThe ruling Justice and Development party (AKP) and an allied nationalist party won more than half of the votes across Turkey as a whole. But despite almost blanket pro-government media coverage, they lost Istanbul, the country’s economic and cultural powerhouse, as well as the capital, Ankara, breaking Islamist parties’ control of the two cities for the first time in a quarter of a century.', 'dunya', 'https://i.guim.co.uk/img/media/f923ea65b28c4c5ecf21cc5b440f5f002d917da5/0_51_2553_1531/master/2553.jpg?width=620&quality=85&auto=format&fit=max&s=58283ee5fd5ee42c6272d918afef1d05', 0, 0, 0, '2019-04-26 20:20:38'),
(9, 'Son dakika… TBMM\'de 23 Nisan özel oturumu', 'TBMM Genel Kurulu, Meclisin açılışının 99. yıl dönümü ile 23 Nisan Ulusal Egemenlik ve Çocuk Bayramı dolayısıyla özel gündemle toplandı.\r\n\r\nGenel Kurul, TBMM Başkanı Mustafa Şentop\'un başkanlığında açıldı. İstiklal Marşı\'nın okunmasının ardından Şentop konuşmasına başladı.\r\n\r\nCumhurbaşkanı Recep Tayyip Erdoğan\'ın da izlediği Genel Kurul\'a, liderlerden ilk olarak MHP Genel Başkanı Devlet Bahçeli, ardından CHP Genel Başkanı Kemal Kılıçdaroğlu geldi.\r\n\r\nErdoğan\'ı locaya gelişinde AK Parti Grubu ayakta alkışlarken, MHP Grubu da ayakta karşıladı.', 'gundem', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbef6090f25441e0c108326.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(10, 'Almanya\'nın silah ihracatı ilk çeyrekte düştü', 'Alman hükümeti, bu yılın ilk çeyreğinde 1 milyar 120 milyon avroluk silah ve askeri malzeme satışına onay verdİ.\r\n\r\nAlmanya\'nın silah ve askeri malzeme satışı, bu yılın ilk çeyreğinde 2018\'in aynı dönemine göre yaklaşık yüzde 8 düştü.\r\n\r\nAlmanya Ekonomi ve Enerji Bakanlığının Yeşiller Partisi\'nden bir milletvekilinin soru önergesine verdiği yanıta göre, Alman hükümeti, bu yılın ilk çeyreğinde 1 milyar 120 milyon avroluk silah ve askeri malzeme satışına onay verdi. \r\n\r\nGeçen yılın ilk çeyreğinde 1 milyar 210 milyon avro olan silah satışı, 2019\'un aynı döneminde yaklaşık yüzde 8 düşüşe (100 milyon avro) işaret etti. \r\nAlmanya\'nın bu yılın ilk çeyreğinde en fazla silah satışı yaptığı ülke 169 milyon avro ile ABD oldu. ABD\'yi, 157 milyon avro ile İngiltere, 88 milyon avro ile Avustralya ve 56 milyon avro ile Fas izledi. ', 'ekonomi', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbef9b60f25441e0c1083b5.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(11, 'AB\'de bütçe açığı azaldı', 'AB\'de geçen yıl bütçe açığının GSYH\'ye oranı düştü.\r\n\r\nAvrupa Birliği\'nde (AB) bütçe açığının GSYH\'ye oranı geçen yıl yüzde 0,6\'ya indi.\r\n\r\nAvrupa İstatistik Ofisi (Eurostat), AB ve Avro Bölgesi\'nin 2018 yılı bütçe açığı ve kamu borcu verilerini yayımladı. \r\nBuna göre, 28 üyeli AB\'de 2017\'de yüzde 1 olan bütçe açığının GSYH\'ye oranı, 2018\'de yüzde 0,6\'ya düştü. \r\nAvro Bölgesi\'nde ise bütçe açığının GSYH\'ye oranı, söz konusu dönemde yüzde 1\'den yüzde 0,5\'e geriledi. \r\n\r\nKAMU BORCU \r\n\r\nAB\'de 2017\'de yüzde 81,7 olan kamu borcunun GSYH\'ye oranı, geçen yıl yüzde 80\'e indi. \r\nAvro Bölgesi\'nde ise kamu borcunun GSYH\'ye oranı, aynı dönemde yüzde 87,1\'den yüzde 85,1\'e geriledi. \r\n\r\nAB üyesi ülkeler arasında 2018\'de kamu borcunun GSYH\'ye oranı en fazla olan ülke yüzde 181,1 ile Yunanistan olarak belirlendi. Yunanistan\'ı, yüzde 132,2 ile İtalya, yüzde 121,5 ile Portekiz, yüzde 102,5 ile Güney Kıbrıs Rum Yönetimi ve yüzde 102 ile Belçika izledi. \r\n\r\nSöz konusu dönemde kamu borcunun GSYH\'ye oranı en az olan ülke ise yüzde 8,4 ile Estonya, yüzde 21,4 ile Lüksemburg ve yüzde 22,6 ile Bulgaristan oldu. ', 'ekonomi', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbef9630f25441e0c1083a2.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(12, '100 milyon dolarlık fuar', 'İstanbul Uluslararası Ev Tekstili Fuarı (EVTEKS), binin üzerinde markanın katılımıyla kapılarını açtı.\r\n\r\nAlanında dünyanın en büyük iki etkinliğinden biri olan ve 120 ülkeden yabancı alıcıları ağırlayan EVTEKS, CNR Expo Yeşilköy\'de ziyarete açıldı. \r\n\r\nFuarın açılışında konuşan Türkiye İhracatçılar Meclisi (TİM) Başkanı İsmail Gülle, fuarın 25. yıl dönümünde olduğunu hatırlatarak, çeyrek asırlık bir emek bulunduğunu, başarılı organizasyonun Türkiye\'nin yüz akı olduğunu söyledi. \r\n\r\nGülle, yolcuların beraberinde götürdüğü kargoların da ihracata katılmasına ilişkin yapılan düzenlemeye değinirken, şu değerlendirmelerde bulundu: \r\n\"Mart ayında, özellikle yolcu beraberinde kargoyla yapılan mikro ihracatların da kayıt altına alınmasıyla ilgili düzenleme yapıldı. Bu düzenleme, inşallah diğer bölgelerimizde de hayata geçtiğinde hem ihracatımızdaki rasyonel artışı hem de ev tekstilinin gerçek gücünü görmek için çok faydalı olacak. Bu fuar bize, sektörlerin büyüdüğünü, geliştiğini ve artık mızrağın çuvala sığmadığını gösterdi. Bu mekanlar artık bize yetmiyor.\" \r\n\r\nGülle, Atatürk Havalimanı arazisine kurulacak fuar merkezi ile Türkiye\'nin ihracatında ciddi artış sağlanacağını vurgulayarak, fuarların uluslararası ticarete sağladığı katkıya işaret etti. \r\n\r\nEVTEKS\'in önemine değinen Gülle, \"Ev tekstilinde; fuarcılıkta dünya ikinciliği, ihracatta dünya dördüncülüğü var. Sektörün önü açık.\" dedi. \r\n\r\n\"EV TEKSTİLİNDE ÜRETİCİLİKTEN ÇIKIP TREND BELİRLEYEN OLDUK\"\r\n\r\nİstanbul Ticaret Odası (İTO) Başkanı Şekib Avdagiç de fuarın 25. yılında olmasından iftihar duyduğunu, aradan geçen çeyrek asırlık süreçte etkinliğin uluslararası bir organizasyon haline geldiğini söyledi. \r\n\r\nFuar merkezinin daha da büyütülmesi konusunda gayret göstereceklerini ifade eden Avdagiç, \"İstanbul\'u 100 bin metrekarelik fuar merkezinden 200, 300, 400 bin metrekarelik fuar merkezine taşıyacağız. Bu şekilde sadece bu fuarı değil, birçok fuarımızı daha İstanbul\'da daha büyük katılımla yapma ve çok sayıda fuarı bu ', 'ekonomi', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbef44e0f25441e0c108306.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(13, 'Muğdat Çelik, kolayı yapamadı', 'Galatasaraylı futbolcu Muğdat Çelik, Hatayspor savunmasının hatasında boş kaleye topu gönderemedi.\r\n\r\nHatayspor kalecisi Ömer Alıcı\'nın paslaşarak kullandığı aut atışında ceza sahasının sağında topu alan Soner Örnek, pasını yeniden Ömer\'e aktarmak istedi. Ancak kalecinin önüne düşen topta araya giren Muğdat, bekletmeden boş kaleye vuruşunu yaptı ancak top üstten auta çıktı.', 'spor', 'https://ajssarimg.mediatriple.net/943719.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(14, 'TBMM Başkanı Şentop: Kılıçdaroğlu\'na yönelik müessif saldırıyı kınıyorum', 'Türkiye\r\n14:49 23.04.2019URL\'yi kısaltın\r\n0 10\r\n\r\nÇubuk\'taki cenaze töreninde CHP Genel Başkanı Kemal Kılıçdaroğlu\'na yönelik linç girişimiyle ilgili konuşan TBMM Başkanı Mustafa Şentop, \"CHP Genel Başkanı Sayın Kemal Kılıçdaroğlu\'na ve bazı milletvekili arkadaşlarımıza yönelik saldırı gerçekleşmiştir. Bu müessif saldırıyı kınıyorum. Bir daha bu tür hadiselerin yaşanmaması en büyük temennimizdir\'\' dedi.\r\nTBMM Tören Salonu\'nda gerçekleştirilen tören, Şentop\'un yerini almasının ardından İstiklal Marşı\'nın okunmasıyla başladı.  TBMM Genel Kurulu, Meclisin açılışının 99. yıl dönümü ile 23 Nisan Ulusal Egemenlik ve Çocuk Bayramı dolayısıyla özel gündemle toplandı.\r\n\r\nGenel Kurul, TBMM Başkanı Mustafa Şentop\'un başkanlığında açıldı. İstiklal Marşı\'nın okunmasının ardından Şentop konuşmasına başladı.', 'gundem', 'https://cdntr1.img.sputniknews.com/images//103885/01/1038850106.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(15, 'Erdoğan\'dan Kılıçdaroğlu açıklaması: Ne yazık ki bir şehidimizin cenaze töreninde istenmeyen bir olay meydana geldi', 'Cumhurbaşkanı Recep Tayyip Erdoğan, CHP lideri Kılıçdaroğlu\'nun dün Ankara\'da katıldığı şehit cenazesinde saldırıya uğramasıyla ilgili olarak \"Ne yazık ki dün Çubuk’ta bir şehidimizin cenaze töreninde istenmeyen bir olay meydana gelmiş, CHP Genel Başkanı Kemal Kılıçdaroğlu’na yönelik protestolar şiddet eylemine dönüşmüştür\" dedi.\r\n\r\nCHP lideri Kemal Kılıçdaroğlu\'nun dün Ankara Çubuk\'ta katıldığı şehit cenazesinde saldırıya uğramasıyla ilgili olarak Twitter hesabından açıklamalarda bulunan Erdoğan, şunları söyledi:\r\n\r\n\"Dün dört şehidimizi toprağa verdik. Allah şehitlerimize gani gani rahmet eylesin. Bu vatan onların bize bıraktığı kutsal bir emanettir.\"', 'gundem', 'https://cdntr1.img.sputniknews.com/images/103866/31/1038663104.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(16, 'Sri Lanka bombings ‘retaliation’ for New Zealand mosques massacre – minister ', 'A man holds a cross during a mass burial of victims at a cemetery near St. Sebastian Church in Negombo © REUTERS/Athit Perawongmetha; A view of the dome of Al Noor mosque, where the shooting took place, in Christchurch \r\nThe serial bombing of Christian churches and hotels in Sri Lanka may have been an act of retaliation for the gun rampage at mosques in Christchurch, New Zealand, a Sri Lankan minister said citing the initial investigation.\r\n\r\nTwo domestic Islamist groups, the National Thawheed Jama’ut and the Jammiyathul Millathu Ibrahim, are suspected by investigators of orchestrating the Easter Sunday bombings, which killed over 300 people, Ruwan Wijewardene, Sri Lanka’s junior defense minister, told MPs.', 'dunya', 'https://cdni.rt.com/files/2019.04/article/5cbee29adda4c8204e8b4576.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(17, 'Gorillas perfect their selfie style in photo with park ranger', 'Ndakazi and Ndeze pose with a park ranger at Virunga National Park in the Democratic Republic of Congo.\r\n\r\n(CNN)Two gorillas have been snapped apparently mimicking human behavior, in a remarkable selfie with a park ranger who helped rescue them as babies.\r\nThe photo, taken by a worker at Virunga National Park in the Democratic Republic of Congo, swiftly went viral after being shared on Facebook.\r\n\"Another day at the office...\" Mathieu Shamavu wrote alongside the image, which has been shared more than 20,000 times.\r\n\r\nFemale gorillas Ndakazi and Ndeze appear to be naturals in front of the camera; one stands proudly in a power pose with her feet wide apart, while the other leans forward to make it into the shot.', 'dunya', 'https://cdn.cnn.com/cnnnext/dam/assets/190422153943-gorillas-selfie-virunga-national-park-exlarge-169.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(18, 'Türkiye-Azerbaycan ticaret hacmini 5 milyar dolara çıkarmayı hedefliyoruz', 'Ankara Ticaret Odası (ATO) Başkanı Gürsel Baran, Türkiye ile Azerbaycan arasında 2 milyar dolar civarında bir ticaret hacmi olduğunu belirterek, \"Her iki ülkenin de katkısıyla bu rakamın kısa sürede 5 milyar dolar olmasının önünde hiçbir engel bulunmadığını düşünüyorum.\" dedi.\r\nTürk Hava Yolları\'nın (THY) başlattığı ilk direkt Ankara-Bakü seferiyle Azerbaycan\'a gelen ATO Başkanı Baran, gazetecilere yaptığı açıklamada, Türkiye ve Azerbaycan\'ın dini, dili, geçmişi ve tarihinin bir olduğunu söyledi.\r\nBöyle bir ülkeye Ankara\'dan doğrudan uçuş yapılmamasının doğru olmadığını, bu açığı kapattıklarını belirten Baran, uçuşun iki ülkenin daha da yakınlaşması anlamında hayırlı olmasını diledi. Baran, uçuşun hem Bakü hem de Ankara\'nın ekonomisine önemli katkı sağlayacağını vurguladı.', 'ekonomi', 'http://idora.gazetevatan.com/vatanmediafile/Haber598x362/2019/04/23/-turkiye-azerbaycan-ticaret-hacmini-5-milyar-dolar-4057678.Jpeg', 0, 0, 0, '2019-04-26 20:20:38'),
(19, 'Eljif Elmas için İstanbul\'a geldiler!', 'Premier Lig ekibi Tottenham\'ın izlediği ve Inter\'in de takip ettiği iddia edilen Eljif Elmas\'a bir talip daha çıktı.\r\n Fenerbahçe\'nin 19 yaşındaki yıldızı Eljif Elmas\'a Avrupa\'dan talipleri artıyor.\r\n \r\nTorino yetkilileri Elmas için geldi\r\n \r\nDaha önce Premier Lig ekibi Tottenham\'ın Türkiye\'ye gelip izlediği ve Inter\'in de takipte olduğu iddia edilen Makedon yıldız Eljif\'e İtalya\'dan bir talip daha çıktı. Serie A ekibi Torino da Elmas\'ı takip etmeye başladı. Torino ekibinin yetkilileri Türkiye\'ye gelip Elmas\'ın maçlarını izledi.', 'spor', 'http://idora.gazetevatan.com/vatanmediafile/Sampiyon620x350/2019/04/23/eljif-elmas-icin-istanbul-a-geldiler--4057830.Jpeg', 0, 0, 0, '2019-04-26 20:20:38'),
(20, 'Bucks 18 yıl sonra tur atladı', 'Milwaukee Bucks, Detroit Pistons ile oynadığı NBA Doğu Konferansı play-off ilk tur serisini 4-0 kazanarak 18 yıl sonra konferans yarı finaline çıktı.\r\n Amerikan Basketbol Ligi\'nde (NBA) Detroit Pistons\'ı 127-104 yenen Milwaukee Bucks, play-off ilk tur serisini 4-0 kazandı.\r\n \r\nNBA play-off\'larına 2 maçla devam edildi. Milwaukee Bucks, Detroit Pistons\'a konuk olduğu Doğu Konferansı play-off ilk tur 4. karşılaşmasından 127-104 galip ayrıldı ve seriyi 4-0 üstünlükle tamamladı.\r\n \r\n2001\'den bu yana ilk kez play-off\'larda tur atlayan Bucks, konferans yarı finalinde Boston Celtics\'in rakibi oldu.\r\n \r\nBucks\'ın all-star forveti Giannis Antetokounmpo, 41 sayıyla play-off kariyerinin en yüksek skoruna ulaştı. Khris Middleton 18 sayı, Eric Bledsoe 16 sayı, 5 asist ve Ersan İlyasova 4 sayı, 9 ribaunt, 3 asist üretti.\r\n \r\nPistons\'ta Reggie Jackson\'ın 26 sayı, 7 asist, Blake Griffin\'in 22 sayı, 6 asist, 5 ribaunt ve Andre Drummond\'ın 15 sayı, 12 ribauntluk performansı mağlubiyeti önleyemedi.', 'spor', 'http://idora.gazetevatan.com/vatanmediafile/Sampiyon620x350/2019/04/23/bucks-18-yil-sonra-tur-atladi-4057373.Jpeg', 0, 0, 0, '2019-04-26 20:20:38'),
(21, 'Beşiktaş\'ta kriz büyüyor! İdmanda protesto...', 'Beşiktaş Sompo Japan’da yerli oyuncular maaşlarını alamadıkları gerekçesiyle yabancılardan ayrı idman yaparak durumu protesto etti.\r\n Beşiktaş Sompo Japan\'da oyuncular ve personel maaş sıkıntısı yaşamaya devam ediyor.\r\n \r\nSiyah-beyazlı yönetim basketbolculara bu ayın ortasına kadar ödeme sözü vermesine rağmen verilen vaatler yerine getirilmedi. Beşiktaş Sompo Japan\'da yabancı basketbolcular maaşlarını 2 ay, yerliler de 5 ay geriden alıyor.\r\n \r\nYABANCILARDAN AYRI\r\n \r\nSiyah-beyazlı takımın dünkü idmanında yerli basketbolcular maaşlarında yaşanan gecikme nedeniyle yabancılardan ayrı bir şekilde çalıştı. Böylece yerliler ödenmeyen paralar için yönetimi protesto etti. ', 'spor', 'http://idora.gazetevatan.com/vatanmediafile/Sampiyon620x350/2019/04/19/besiktas-ta-kriz-buyuyor-idmanda-protesto--4053666.Jpeg', 0, 0, 0, '2019-04-26 20:20:38'),
(22, 'Starbucks rolls out drug needle disposal bins to follow up addict-friendly open bathroom policy ', ' Starbucks is installing needle-disposal boxes in its US bathrooms after getting fined over its lack of response to a spike in needle-stick injuries among employees under its addict-friendly “open-door” bathroom policy.\r\n\r\nThe coffee behemoth has installed the boxes in 25 cities after the Oregon Occupational Safety and Health Administration (OSHA) slapped the company with a $3,100 fine for endangering workers. Starbucks was penalized for failing to provide sharps-disposal containers “in or near bathrooms where contaminated sharps were commonly found,” failing to make the Hepatitis B vaccine available to employees who could be exposed to the disease through contaminated needles, and failing to provide proper training and “exposure-control programs.”', 'dunya', 'https://cdni.rt.com/files/2019.04/article/5cbed857fc7e938d048b4679.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(23, 'Sri Lanka\'s economy is fragile, and it depends on tourism', 'Hong Kong (CNN Business)A series of deadly attacks could deal a body blow to one of Asia\'s fragile economies.\r\nBombs ripped through churches and luxury hotels in Sri Lanka on Easter Sunday, killing at least 290 people and injuring hundreds. Targets included the upmarket Shangri-La hotel in the capital, Colombo.\r\nAt least 39 of those killed in the explosions were identified as tourists from countries including the United Kingdom, Denmark, Australia and India.\r\n\r\nOn top of the heavy loss of human life, the attacks could cause serious damage to Sri Lanka\'s economy, which depends on tourism.', 'dunya', 'https://cdn.cnn.com/cnnnext/dam/assets/190423120305-05-sri-lanka-0423-exlarge-169.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(24, 'EYT\'de Son Gelişmeler', 'EYT YASASI ÇIKACAK MI?\r\n\r\nEYT yasası çıkacak mı, gibi merak edilen soruların Meclis açıldıkta sonra gündeme gelmesi bekleniyor. Seçimler nedeniyle 24 Şubat\'ta çalışmalarına ara veren TBMM 23 Nisan\'dan sonra mesaiye başlayacak. TBMM\'nin açılması ile birlikte gündemde önemli konular olacak. Vatandaşlar EYT ile ilgili de açıklama yapılmasını bekliyor. Meclis açıldıktan sonra konu ile ilgili gelişmeler yaşandıkça aktarmaya devam edeceğiz.', 'ekonomi', 'https://iatkv.tmgrup.com.tr/b2f1e5/616/321/0/89/724/467?u=https://itkv.tmgrup.com.tr/2019/04/23/eytde-bugun-son-daikika-23-nisan-emeklilikte-yasa-takilanlar-yasasi-cikacak-mi-mujdeli-haber-var-mi-1556003130815.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(25, 'Kamu bankalarına 3.7 milyar €', 'Hazine ve Maliye Bakanı Berat Albayrak, Devlet İç Borçlanma Senedi (DİBS) ihracına ilişkin açıklamalar yaptı. Yapısal Dönüşüm Adımları ile söz verdikleri politikaları hayata geçirdiklerini belirten Bakan Albayrak, \"Kamu bankalarımıza, sermayelerini güçlendirmek için 3.7 milyar euro ikrazen Devlet İç Borçlanma Senedi verilmesi sürecini tamamladık\" ifadesini kullandı. ', 'ekonomi', 'https://iatkv.tmgrup.com.tr/0907c2/616/321/0/60/800/477?u=https://itkv.tmgrup.com.tr/2019/04/23/kamu-bankalarina-37-milyar--1555970471216.jpeg', 0, 0, 0, '2019-04-26 20:20:38'),
(26, 'Feghouli son anda yetişti', 'F.Bahçe ile oynanan derbi maçta sakatlanan Sofiane Feghouli, Kayserispor maçına yetiştirildi. Derbiden sonra sol alt arka adale grubunda zorlama ve kanama tespit edilen Feghouli, yapılan tedavinin ardından Kayseri ekibi karşısında ilk 11\'deki yerini aldı. Martin Linnes ise dün kulübeye çekildi.', 'spor', 'https://iatkv.tmgrup.com.tr/818e2e/616/321/0/30/800/446?u=https://itkv.tmgrup.com.tr/2019/04/21/feghouli-son-anda-yetisti-1555796431003.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(27, 'Hakan Çalhanoğlu\'nun Milan dönemi bitti! Yeni rotası...', 'İtalya Serie A ekiplerinde Milan\'da forma giyen Hakan Çalhanoğlu için İtalya basınından flaş bir iddia ortaya atıldı. Buna göre; Milan\'da 25 yaşındaki oyuncunun yeni adresi de duyuruldu.\r\n\r\nİtalya\'nın önde gelen basın kuruluşları, Milli futbolcumuz Hakan Çalhanoğlu\'nun transferini açıkladı.\r\n\r\nHaberde, Milan\'ın para kazanma kapmasında Hakan Çalhanoğlu\'nu sezon sonunda satacağı ifade edildi. Serie A ekibinin, milli futbolcudan en az 20 milyon euro kazanmayı hedeflediği kaydedildi.\r\n\r\nMilan ile 2021\'e dek sözleşmesi bulunan Hakan Çalhanoğlu, bu sezon 40 maçta 2 gol attı ve 13 asist yaptı.\r\nİtalyada Juventus, Fransada PSG ipi göğüsledi\r\nİtalya\'da Juventus, Fransa\'da PSG ipi göğüsledi ', 'spor', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbecbf2c03c0e40ecf49694.jpg', 0, 0, 0, '2019-04-26 20:20:38'),
(28, 'Son dakika: YSK, KHK\'lıların oy kullanabileceğine karar verdi', 'AK Parti\'nin KHK\'lıların oy kullanmaması yönündeki itirazı YSK tarafından reddedildi.\r\n\r\nİstanbul seçimleriyle ilgili olağanüstü itirazları görüşen YSK, KHK\'lıların oy kullanabileceğine karar verdi.', 'gundem', 'http://i.hurimg.com/i/hurriyet/75/750x422/5cbf0181c03c0e40ecf49c66.jpg', 0, 0, 0, '2019-04-26 20:20:38');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `news`
--
ALTER TABLE `news`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
